name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Linux
      run: swift test

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Android
      uses: skiptools/swift-android-action@v2

  macos:
    name: macOS, iOS, tvOS, Mac Catalyst (Xcode)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test macOS
      run: xcodebuild test -scheme SwiftCBOR -destination 'platform=OS X,arch=x86_64'
    - name: Test iOS
      run: xcodebuild test -scheme SwiftCBOR -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'
    - name: Test tvOS
      run: xcodebuild test -scheme SwiftCBOR -destination 'platform=tvOS Simulator,name=Any tvOS Simulator Device'
    - name: Test Mac Catalyst
      run: xcodebuild test -scheme SwiftCBOR -destination 'platform=macOS,variant=Mac Catalyst'
